run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 5
  tests: false
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
linters:
  enable-all: true
  disable:
    - maligned
    - nosnakecase
    - structcheck
    - exhaustivestruct
    - interfacer
    - varcheck
    - golint
    - deadcode
    - scopelint
    - ifshort
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - wsl
    - gci
    - gofmt
    - gofumpt
    - goimports
    - nlreturn
    - noctx
    - exhaustruct
    - wrapcheck
  fast: false
issues:
  exclude:
    - G107